In [1]:
import utils.datasets as DB

In [2]:
datasets = DB.Datasets()

In [3]:
train_mnist, test_mnist = datasets.get_MNIST()

print(len(train_mnist))
print(train_mnist[6])

print(len(test_mnist))
print(test_mnist[6])

60000
(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 

In [4]:
train_regr, test_regr = datasets.get_regression()

print(len(train_regr))
print(len(test_regr))

print(train_regr[6])
print(test_regr[6])

2023-02-18 00:34:32,560 [INFO] get_regression method called
2023-02-18 00:34:32,562 [INFO] Found the Files


250
500
(tensor([0.2631], dtype=torch.float64), tensor([0.4767], dtype=torch.float64))
(tensor([-0.0293], dtype=torch.float64), tensor([-0.2298], dtype=torch.float64))
